version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=Fireaway123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
        - C:/oracle-data:/opt/oracle/oradata
    networks:
      - fireaway-network
    restart: unless-stopped



  fireaway-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fireaway-api
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=fireaway
      - SPRING_DATASOURCE_PASSWORD=Fireaway123
      - JWT_SECRET=n0DpN8vpYlZx4K5GlqsfTejKu3CwFmRtuWZ3rJ+wZTT3XY8mEK6S9Fg7b8vtlXcVzNQSTaVq6XcNc8jw7coA9g==
    restart: always
    networks:
      - fireaway-network
    command: ["./wait-for-it.sh", "oracle-db:1521", "--", "java", "-jar", "app.jar"]

volumes:
  oracle-data:

networks:
  fireaway-network:
